POST http://localhost:5220/auth/register
Content-Type: application/json

{
    "firstName": "Harish",
    "lastName" : "Raju",
    "email" : "harisharaju1@gmail.com",
    "password" : "qwerty123456"
}